% EEC-201, Winter Quarter 2021, Final Project
%
% Title: Plot Codebooks
%
% Description: This functions will plot codebooks generated by the VQ
% algorithm.  Mix and match 2-D and 3-D feature spaces with the codebook
% recipie  input.
%
% Authors: Igor Sheremet and Jonathan Tivald
%
% Date: 3/5/2021

function status = plot_codebooks(mfcc, codebooks, spkr_plt)

    % Read in the codebook centroids to plot
    load('codebook.mat','centroids','min_distort_idx');

    % plot codebooks
    figure('Name',strcat('Speaker ',num2str(spkr_plt),' Codebooks'))

    for i = 1:size(codebooks,1)

        subplot(2,ceil(size(codebooks,1)/2),i)

        % Make life easier, save temp matrix of centroids and
        % Min distortion index from cell array
        cent_mat = centroids{i,spkr_plt};
        min_dist_vec = min_distort_idx{i,spkr_plt};
        mfcc_mat = mfcc{1,spkr_plt};

        % Generate color palette
        data_clr = lines(size(cent_mat,1));

        if length(find(codebooks(i,:))) == 2

            % 2-D graph

            % Plot centroid and associated MFCCs with matching colors
            for j = 1:size(cent_mat,1)
                
                scatter(cent_mat(j,1),...
                        cent_mat(j,2),...
                        [],data_clr(j,:),'filled')

                hold on

                scatter(mfcc_mat(codebooks(i,1),min_dist_vec==j),...
                        mfcc_mat(codebooks(i,2),min_dist_vec==j),...
                        [],data_clr(j,:))
            end

            title(strcat('Codebook',num2str(i)))
            xlabel(strcat('MFCC',num2str(codebooks(i,1))))
            ylabel(strcat('MFCC',num2str(codebooks(i,2))))
        else

            % 3-D graph

            % Plot centroid and associated MFCCs with matching colors
            for j = 1:size(cent_mat,1)
                
                scatter3(cent_mat(j,1),...
                        cent_mat(j,2),...
                        cent_mat(j,3),...
                        [],data_clr(j,:),'filled')

                hold on

                scatter3(mfcc_mat(codebooks(i,1),min_dist_vec==j),...
                        mfcc_mat(codebooks(i,2),min_dist_vec==j),...
                        mfcc_mat(codebooks(i,3),min_dist_vec==j),...
                        [],data_clr(j,:))
            end

            title(strcat('Codebook',num2str(i)))
            xlabel(strcat('MFCC',num2str(codebooks(i,1))))
            ylabel(strcat('MFCC',num2str(codebooks(i,2))))
            zlabel(strcat('MFCC',num2str(codebooks(i,3))))
        end
    end

    %return a status flag
    status = 1;
end