% EEC-201, Winter Quarter 2021, Final Project
%
% Title: Plot Codebooks
%
% Description: This functions will plot codebooks generated by the VQ
% algorithm.  Mix and match 2-D and 3-D feature spaces with the codebook
% recipie  input.
%
% Authors: Igor Sheremet and Jonathan Tivald
%
% Date: 3/5/2021

function status = plot_codebooks(mfcc, codebooks, spkr_plt)

    % Read in the codebook centroids to plot
    load('codebook.mat','centroids');

    % plot codebooks
    figure('Name',strcat('Speaker ',num2str(spkr_plt),' Codebooks'))

    for i = 1:size(codebooks,1)

        subplot(2,ceil(size(codebooks,1)/2),i)

        if length(find(codebooks(i,:))) == 2
            %2-D graph
            scatter(mfcc{1,spkr_plt}(codebooks(i,1),1:71),mfcc{1,spkr_plt}(codebooks(i,2),1:71))
            hold on
            scatter(centroids{i,spkr_plt}(:,1),centroids{i,spkr_plt}(:,2),[],'filled')
            title(strcat('Codebook',num2str(i)))
            xlabel(strcat('MFCC',num2str(codebooks(i,1))))
            ylabel(strcat('MFCC',num2str(codebooks(i,2))))
        else
            %3-D graph
            scatter3(mfcc{1,spkr_plt}(codebooks(i,1),1:71),mfcc{1,spkr_plt}(codebooks(i,2),1:71),mfcc{1,spkr_plt}(codebooks(i,3),1:71))
            hold on
            scatter3(centroids{i,spkr_plt}(:,1),centroids{i,spkr_plt}(:,2),centroids{i,spkr_plt}(:,3),[],'filled')
            title(strcat('Codebook',num2str(i)))
            xlabel(strcat('MFCC',num2str(codebooks(i,1))))
            ylabel(strcat('MFCC',num2str(codebooks(i,2))))
            zlabel(strcat('MFCC',num2str(codebooks(i,3))))
        end
    end

    %return a status flag
    status = 1;
end